#!/usr/bin/env bash



#prompt
RED="%F{red}"
YELLOW="%F{yellow}"
GREEN="%F{green}"
WHITE="%F{white}"
NOCOLOR="%f"

todays_note_file=`soji note-path log`
pom_count=`cat $todays_note_file 2> /dev/null | grep -i "** start" | wc -l | sed "s/^ *//"`
poms=""
if [ $pom_count -lt 4 ]; then
  poms="$WHITE pomodoros $RED $pom_count"
elif [ $pom_count -lt 8 ]; then
  poms="$WHITE pomodoros $YELLOW $pom_count"
else
  poms="$WHITE pomodoros $GREEN $pom_count"
fi

lunch=""
cat $todays_note_file 2> /dev/null | grep -i "** lunch" &> /dev/null
if [[ $? == 0 ]]; then
  lunch="$WHITE lunch $GREEN[✔]"
else
  lunch="$WHITE lunch $RED[✘]"
fi

meeting_count=`cat $todays_note_file 2> /dev/null | grep -i "** meeting" | wc -l | sed "s/^ *//"`
meetings="$WHITE meetings $GREEN $meeting_count"

echo "$lunch $poms $meetings $RED $(soji status) $NOCOLOR"
